# -*- mode: python ; coding: utf-8 -*-

import os

a = Analysis(
    ['interface.py'],
    pathex=[os.getcwd()],
    binaries=[],
    datas=[
        ('crowico.png', '.'),
        ('core', 'core'),
    ],
    hiddenimports=[
        'ctypes',
        'ctypes.windll',
        'ctypes.wintypes',
        'string',
        'enum',
        'dataclasses',
        'pathlib',
        'stat',
        'subprocess',
        'threading',
        'time',
        'os',
        'sys',
        'queue',
        'PyQt5',
        'PyQt5.sip',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'core.base',
        'core.limpeza',
        'core.modo_rapido',
        'core.modo_normal',
        'core.modo_seguro',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'numpy',
        'pandas',
        'matplotlib',
        'PIL',
        'curses',
        'test',
        'unittest',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='cleancrow',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='crowico.png',
    uac_admin=True,
)